language: go

go_import_path: github.com/puma/puma-dev

go:
  - "1.13.x"
  # - master

os:
  # - linux
  - osx

install:
  - go get -t ./...

before_script:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        sudo mkdir -p /etc/resolver;
        sudo chmod 0775 /etc/resolver;
        sudo chown :travis /etc/resolver;
      fi

script:
  - make test
