language: go

go_import_path: github.com/puma/puma-dev

go:
  - "1.13.x"
  # - master

os:
  # - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      sudo mkdir -p /etc/resolver;
      sudo chmod 0775 /etc/resolver;
      sudo chown :staff /etc/resolver;

      export DEFAULT_KEYCHAIN="$HOME/Library/Keychains/login.keychain-db";
      rm -rfv $DEFAULT_KEYCHAIN;

      security create-keychain -p travis $DEFAULT_KEYCHAIN && echo "keychain created";
      security unlock-keychain -p travis $DEFAULT_KEYCHAIN && echo "keychain unlocked";
      security set-keychain-settings -t 3600 -u $DEFAULT_KEYCHAIN & echo "keychain unlock timeout set to 60min";
    fi

install:
  - go get -t ./...

script:
  - make test
