language: go

go_import_path: github.com/puma/puma-dev

go:
  - "1.13.x"
  - master

os:
  - linux
  - osx

install:
  - go get -t ./...

before_script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      sudo mkdir -p /etc/resolver;
      sudo chmod 0775 /etc/resolver;
      sudo chown :staff /etc/resolver;
    fi
  - rvm install 2.7.0
  - rvm --default use 2.7.0
  - gem install puma
  - sudo echo -e "127.0.0.1    hipuma.test rack-hi-puma.localhost" >> /etc/hosts

script:
  - make test
