version: 2.1

commands:
  macos_install_puma:
    steps:
      - run:
          name: ruby-2.6
          command: |
            echo 'chruby ruby-2.6' >> $BASH_ENV
      - run:
          name: Install Puma
          command: |
            gem install puma

  macos_prepare_filesystem:
    steps:
      - run:
          name: allow puma-dev to modify /etc/resolver
          command: |
            sudo mkdir -p /etc/resolver;
            sudo chmod 0775 /etc/resolver;
            sudo chown :staff /etc/resolver;

  macos_install_go:
    steps:
      - run:
          name: install go-1.12
          command: |
            brew install go@1.12
            echo 'export PATH="/usr/local/opt/go@1.12/bin:$PATH"' >> $BASH_ENV

  go_test:
    steps:
      - checkout
      - run: go version
      - run: go mod download
      - run: go test -v -race -coverprofile=coverage.out -covermode=atomic -timeout=60s ./...

jobs:
  test_macos_catalina:
    macos:
      xcode: 11.4.0
    working_directory: /Users/distiller/go/src/puma/puma-dev
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
      GO111MODULE: "on"
      GOPATH: "/Users/distiller/go"
    steps:
      - macos_install_go
      - macos_install_puma
      - macos_prepare_filesystem
      - go_test

  test_macos_mojave:
    macos:
      xcode: 11.1.0
    working_directory: /Users/distiller/go/src/puma/puma-dev
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
      GO111MODULE: "on"
      GOPATH: "/Users/distiller/go"
    steps:
      - macos_install_go
      - macos_install_puma
      - macos_prepare_filesystem
      - go_test

workflows:
  version: 2
  test:
    jobs:
      - test_macos_catalina
      - test_macos_mojave

