name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        #os: [macos-latest, ubuntu-latest]
        #go-version: [1.13.x, 1.14.x]
        os: [macos-latest]
        go-version: [1.13.x]
        ruby-version: [2.5]

    runs-on: ${{ matrix.os }}
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off

    name: puma-dev ${{ matrix.go-version }} ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - uses: actions/checkout@v2
        with:
          path: ./src/github.com/puma/puma-dev

      - run: |
          gem install puma

      - if: ${{ matrix.os == 'macos-latest' }}
        run: |
          sw_vers
          sudo mkdir -p /etc/resolver;
          sudo chmod 0775 /etc/resolver;
          sudo chown :staff /etc/resolver;

      - run: |
          go version
          go mod download
          go test -v -race -coverprofile=coverage.out -covermode=atomic -timeout=300s ./...
